version: '3'
# Docker Sonarr Compose File

services:
  sonarr:

    image: linuxserver/sonarr
    container_name: sonarr
    privileged: true
    restart: always
    ports:
      - 8988:8989

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker-sonarr/config:/config

      # Map in your Media Shares & Download Client's Share(s)...
      - /nas:/nas

    environment:
      - TZ=UTC
      - PGID=0
      - PUID=0

    healthcheck:
      test: curl --fail -s http://localhost:8988/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3